on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.akasaradiskret.org
        username: we.are@akasaradiskret.org
        password: ${{ secrets.ftp_password }}
        exclude: |
          **/.git*
          **/.git*/**
          database.sql
          README.md